[package]
name = "image_simulator_outline"
version = "0.1.0"
edition = "2024"

[dependencies]

ndarray = { version =  "0.16.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.149"
ndarray-rand = "0.15.0"
bincode2 = "2.0.1"
rkyv = "0.8.10"
bytes = "1.11.0"
memmap2 = "0.5"